name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # Build and test
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
  
  # Publish to nuget
  deploy:
    name: Publish NuGet Package
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: CoffeeToolkit/CoffeeToolkit.csproj
        PACKAGE_NAME: CoffeeToolkit
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        
    
