name: CICD

on:
  push:
    branches:
    - main
    - staging
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        VERSION=$(date +"%Y.%m.%d.%H%M")
        if [ "$BRANCH_NAME" = "staging" ]; then
          VERSION="$VERSION-beta"
        fi
        dotnet pack --no-build --configuration Release -p:PackageVersion=$VERSION --output ./nuget
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish to Nuget
      run: dotnet nuget push nuget/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate 